server:
  port: 8087

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://aicyber-nf-w.mysql.rds.aliyuncs.com:3306/ai_robot?useUnicode=true&characterEncoding=utf-8&useSSL=false
    url: jdbc:mysql://localhost:3306/serverless?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root


mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml,classpath:mybatis/mapper/*/*.xml


redis:
  host: 127.0.0.1
  #  host: 47.94.194.124
  port: 6379
  maxTotal: 1
  maxIdle: 1
  maxWaitMillis: 10000
  testOnBorrow: true